### ISSUE TITLE
Cannot read MIDI files come with Windows

### ISSUE THREAD

**Issue by lxfly2000** [rerrahkr/ConvFMML#1]
I tried opening MIDI files at \Windows\Media but none of them was read successfully，is there any limit about the MIDI format？

**Comment by rerrahkr** [comment]
Hi, thank you for your report.  
I found a wrong initialization in reading MIDI, so I have just fixed [it](https://github.com/rerrahkr/ConvFMML/commit/cb7be75d843200e8bd52778d404eb329db7c89f4).
