### ISSUE TITLE
Can it support MoonDriver MML?

### ISSUE THREAD

**Issue by denjhang** [rerrahkr/ConvFMML#3]

**Comment by rerrahkr** [comment]
Depending on whether it is 2OP or 4OP, or OPL3 or OPL4, it is necessary to change the volume and the printing of part names.
To implement these changes, it is necessary to set up multiple styles, which is difficult to implement.
Currently, you can be set a custom style, so you can generate a proper MML by setting it for your specific MoonDriver.

**Comment by rerrahkr** [comment]
And sorry, to be honest, I've lost interest in developing this application and won't be updating it any more.
I'll be archiving the repository, but if you want to further develop this project, you can do so by forking it.
